### ISSUE TITLE
Graphviz times out when visualizing large graphs to SVG

### ISSUE THREAD

**Issue by ReneOschmann** [nidi3/graphviz-java#140]
Hi,

I have a rather big dot-graph I would like to visualize in SVG format. 
In earlier versions I met errors like https://github.com/nidi3/graphviz-java/issues/110, but the workaround there was not helping. In versions 8.5 - 10.0 also smaller graphs did not finish.

With the newest version (12.1) I get timeouts:
```
Exception in thread "main" guru.nidi.graphviz.engine.GraphvizException: Problem in communication with server
	at guru.nidi.graphviz.engine.GraphvizServerEngine.execute(GraphvizServerEngine.java:41)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:224)
	at guru.nidi.graphviz.engine.Renderer.execute(Renderer.java:133)
	at guru.nidi.graphviz.engine.Renderer.toFile(Renderer.java:54)
	at test.test.main(test.java:22)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at guru.nidi.graphviz.engine.Communicator.readStatus(Communicator.java:42)
	at guru.nidi.graphviz.engine.GraphvizServerEngine.lambda$createSvg$0(GraphvizServerEngine.java:75)
	at guru.nidi.graphviz.engine.GraphvizServerEngine.communicating(GraphvizServerEngine.java:103)
	at guru.nidi.graphviz.engine.GraphvizServerEngine.createSvg(GraphvizServerEngine.java:73)
	at guru.nidi.graphviz.engine.GraphvizServerEngine.execute(GraphvizServerEngine.java:39)
	... 4 more
```

This timeout was introduced in https://github.com/nidi3/graphviz-java/issues/74.

**Would it be possible to make to make this timeout configurable?**
Any tips and tricks regarding performance?

Code and file:
```
package test;

import java.io.File;
import java.io.IOException;

import guru.nidi.graphviz.engine.Format;
import guru.nidi.graphviz.engine.Graphviz;
import guru.nidi.graphviz.engine.Renderer;
import guru.nidi.graphviz.model.MutableGraph;
import guru.nidi.graphviz.parse.Parser;

public class test {

	public static void main(String[] args) {
		try {
			Parser p = new Parser();
			System.out.println("Read File");
			MutableGraph g = p.read(new File("<path_to>\\breaking_waitgraph.dot"));
			System.out.println("Render Graph");
			Renderer r = Graphviz.fromGraph(g).render(Format.SVG);
			System.out.println("Write to file");
			r.toFile(new File("<path_to>\\my.svg"));
		} catch(IOException e) {
			System.out.println(e);
		}
		System.out.println("Done");
	}
}
```
[breaking_waitgraph.zip](https://github.com/nidi3/graphviz-java/files/4085436/breaking_waitgraph.zip)

**Comment by joel314** [comment]
Same issue here. Isn't it possible to configure the timeout?

**Comment by ReneOschmann** [comment]
Hi Joel314,

I think it is hard-coded here:
https://github.com/nidi3/graphviz-java/blob/10a5d89d8052fdebbabeca7be7a7d11ce69ce04f/graphviz-java/src/main/java/guru/nidi/graphviz/engine/GraphvizServerEngine.java

```
    private static <T> T communicating(ComFunc<T> action) throws IOException {
        try (final Socket socket = new Socket("localhost", GraphvizServer.PORT);
             final Communicator com = new Communicator(socket, 5000)) {
            return action.apply(com);
        }
    }
```

Kind regards
René

**Comment by joel314** [comment]
Thank you René.

I can see my issue isn't exactly the same as yours, though quite similar. I believe that the timeout that triggers an exception for me is in [(https://github.com/nidi3/graphviz-java/blob/master/graphviz-java/src/main/java/guru/nidi/graphviz/service/CommandLineExecutor.java)], in line 36: 

`final ExecuteWatchdog watchdog = new ExecuteWatchdog(60 * 1000);`

Best Regards,
Joël.

**Comment by nidi3** [comment]
Sorry for the late answer. I tried your monster graph and even the native dot had problems with it.
But making the timeout configurable surely makes sense.

**Comment by joel314** [comment]
That would be really awesome if you could also parametrize the CommandLineExecutor.

**Comment by nidi3** [comment]
ServerEngine and CmdLineEngine have a configurable timeout in version `0.14.2`.

**Comment by joel314** [comment]
Hi Stefan,

I am trying to use the timeout parameter you defined on the `CommandLineExecutor` class in the situation below: 

`
	String dotString = "digraph D {  A -> B -> C }";
	Parser p = new Parser();
	MutableGraph mg = p.read(dotString);
	Graphviz viz = Graphviz.fromGraph(mg);  
	Renderer rend=viz.engine(Engine.DOT).render(Format.PLAIN);
	String output = rend.toString();
	System.out.println(output);
`

I can see that `rend.toString()` calls `Renderer.execute()`, which calls `Graphviz.execute()`, wich calls `GraphvizCmdLineEngine.execute()`, which calls `CommandLineExecutor.execute()`, but it's not clear to me how I could define the timeout in the example above? 

Thanks for your help!
Joël.

**Comment by nidi3** [comment]
The timeout is set on the Engine: `new GraphvizCmdLineEngine().timeout(2,TimeUnit.MINUTES)`

**Comment by joel314** [comment]
Thank you, Stefan. I think it's working fine now: 

String dotString = "digraph D {  A -> B -> C }";
try(GraphvizCmdLineEngine cmdlnEngine = new GraphvizCmdLineEngine()){			
	cmdlnEngine.timeout(2, TimeUnit.MINUTES);
	EngineResult er = cmdlnEngine.execute(dotString, Options.create().format(Format.PLAIN), null); 
	System.out.println(er);
}
