### ISSUE TITLE
NPE when FontConfiguration.getVersion with Open JDK

### ISSUE THREAD

**Issue by GYiyouth** [nidi3/graphviz-java#142]
Hi, I use pure Java to draw picture.

I need to run graphviz-java at Blink cluster
![image](https://user-images.githubusercontent.com/12520517/73651555-9f16f080-46bf-11ea-9c9d-9efc0ba678b8.png)

When I try to render PNG, it will fail

![image](https://user-images.githubusercontent.com/12520517/73651609-bb1a9200-46bf-11ea-9b29-fc6f46e0ee4d.png)

But draw SVG is ok.

my pom like this

```xml
        <dependency>
            <groupId>guru.nidi</groupId>
            <artifactId>graphviz-java-all-j2v8</artifactId>
            <version>0.14.1</version>
        </dependency>
        <dependency>
            <groupId>org.axsl.org.w3c.dom.svg</groupId>
            <artifactId>svg-dom-java</artifactId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>org.w3c.css</groupId>
            <artifactId>sac</artifactId>
            <version>1.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-codec</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-gvt</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-bridge</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-rasterizer</artifactId>
            <version>1.10</version>
            <exclusions>
                <exclusion>
                    <artifactId>batik-parser</artifactId>
                    <groupId>org.apache.xmlgraphics</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>batik-codec</artifactId>
                    <groupId>org.apache.xmlgraphics</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>batik-transcoder</artifactId>
                    <groupId>org.apache.xmlgraphics</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>batik-util</artifactId>
                    <groupId>org.apache.xmlgraphics</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

my code is 
```java
Node
                main = node("main").with(Label.html("<b>main</b><br/>start"), Color.rgb("1020d0").font()),
                init = node(Label.markdown("**_init_**")),
                execute = node("execute").with("href", "http://antmonitor.alipay.com/sofa/view/cif/overview"),
                compare = node("compare").with(Shape.RECTANGLE, Style.FILLED, Color.hsv(.7, .3, 1.0)),
                mkString = node("mkString").with(Label.lines(LEFT, "make", "a", "multi-line")),
                t1 = node("t1").with(Label.nodeName(), Color.ORANGE).with(Style.FILLED, Color.ORANGE).with(Style.ROUNDED, Color.RED),
                printf = node("printf");


        Graph g = graph("example2").directed().with(
                main.link(
                        to(node("parse").link(execute)).with(LinkAttr.weight(8)),
                        to(init).with(Label.html("line1<br/>line2")),
                        node("cleanup"),
                        to(printf).with(Style.BOLD, Label.of("100 times"), Color.RED)),
                execute.link(
                        graph().with(mkString, printf),
                        to(compare).with(Color.RED)),
                init.link(mkString),
                t1
        );

        try {


            ByteArrayOutputStream svgStream = new ByteArrayOutputStream();
            ByteArrayOutputStream pngStream = new ByteArrayOutputStream();
            Graphviz g1 = Graphviz.fromGraph(g).width(900).height(900);
            g1.render(Format.SVG).toOutputStream(svgStream);


            // fail at this line
            g1.render(Format.PNG).toOutputStream(pngStream);

            return new GraphStreamVO(svgStream, pngStream);


        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
```

the full stack :

```log
java.lang.ExceptionInInitializerError
	at org.apache.batik.bridge.SVGTextElementBridge.getFontList(SVGTextElementBridge.java:1529)
	at org.apache.batik.bridge.SVGTextElementBridge.getAttributeMap(SVGTextElementBridge.java:1610)
	at org.apache.batik.bridge.SVGTextElementBridge.fillAttributedStringBuffer(SVGTextElementBridge.java:902)
	at org.apache.batik.bridge.SVGTextElementBridge.buildAttributedString(SVGTextElementBridge.java:856)
	at org.apache.batik.bridge.SVGTextElementBridge.computeLaidoutText(SVGTextElementBridge.java:636)
	at org.apache.batik.bridge.SVGTextElementBridge.buildGraphicsNode(SVGTextElementBridge.java:292)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:224)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:208)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
	at guru.nidi.graphviz.engine.BatikRasterizer.doRasterize(BatikRasterizer.java:46)
	at guru.nidi.graphviz.engine.SvgRasterizer.rasterize(SvgRasterizer.java:35)
	at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:117)
	at guru.nidi.graphviz.engine.Renderer.toOutputStream(Renderer.java:95)
	at guru.nidi.graphviz.engine.Renderer.lambda$toOutputStream$5(Renderer.java:90)
	at guru.nidi.graphviz.engine.EngineResult.mapIO(EngineResult.java:64)
	at guru.nidi.graphviz.engine.Renderer.toOutputStream(Renderer.java:88)
	at com.alipay.dayutrprod.blink.udx.utils.GraphDagUtils.test(GraphDagUtils.java:211)
	at com.alipay.dayutrprod.blink.udx.udf.DrawPngUdf.eval(DrawPngUdf.java:75)
	at StreamExecCalcRule$44.processElement(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingWithOneInputStreamOperatorOutput.pushToOperator(OperatorChain.java:635)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingWithOneInputStreamOperatorOutput.collect(OperatorChain.java:612)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingWithOneInputStreamOperatorOutput.collect(OperatorChain.java:575)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:762)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:740)
	at org.apache.flink.table.runtime.util.StreamRecordCollector.collect(StreamRecordCollector.java:44)
	at StreamExecCorrelateRule$36$TableFunctionCollector$31.collect(Unknown Source)
	at org.apache.flink.table.functions.TableFunction.collect(TableFunction.java:89)
	at com.alibaba.blink.streaming.connectors.common.source.SourceCollectorTableFunction$InternalCollector.collect(SourceCollectorTableFunction.java:83)
	at com.alibaba.blink.streaming.connectors.common.source.parse.DefaultSourceCollector.parseRawMessage(DefaultSourceCollector.java:517)
	at com.alibaba.blink.streaming.connectors.common.source.parse.DefaultSourceCollector.parseAndCollect(DefaultSourceCollector.java:453)
	at com.alibaba.blink.streaming.connector.sls.source.SlsParser.parseAndCollect(SlsParser.java:117)
	at com.alibaba.blink.streaming.connector.sls.source.SlsParser.parseAndCollect(SlsParser.java:55)
	at com.alibaba.blink.streaming.connectors.common.source.SourceCollectorTableFunction.eval(SourceCollectorTableFunction.java:66)
	at StreamExecCorrelateRule$36.processElement(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingWithOneInputStreamOperatorOutput.pushToOperator(OperatorChain.java:635)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingWithOneInputStreamOperatorOutput.collect(OperatorChain.java:612)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingWithOneInputStreamOperatorOutput.collect(OperatorChain.java:575)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:762)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:740)
	at SourceConversion$0.processElement(Unknown Source)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingWithOneInputStreamOperatorOutput.pushToOperator(OperatorChain.java:635)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingWithOneInputStreamOperatorOutput.collect(OperatorChain.java:612)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$ChainingWithOneInputStreamOperatorOutput.collect(OperatorChain.java:575)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:762)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:740)
	at org.apache.flink.streaming.api.operators.StreamSource$1.collectWithMetrics(StreamSource.java:255)
	at org.apache.flink.streaming.api.operators.StreamSource$1.collect(StreamSource.java:242)
	at org.apache.flink.streaming.api.operators.StreamSource$1.collect(StreamSource.java:188)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollectWithTimestamp(StreamSourceContexts.java:310)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collectWithTimestamp(StreamSourceContexts.java:409)
	at com.alibaba.blink.streaming.connectors.common.reader.ParallelReader.processRecord(ParallelReader.java:316)
	at com.alibaba.blink.streaming.connectors.common.reader.ParallelReader.runImpl(ParallelReader.java:289)
	at com.alibaba.blink.streaming.connectors.common.reader.ParallelReader.run(ParallelReader.java:185)
	at com.alibaba.blink.streaming.connectors.common.source.AbstractParallelSourceBase.run(AbstractParallelSourceBase.java:235)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:118)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:72)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:110)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:348)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:727)
	at java.lang.Thread.run(Thread.java:849)
Caused by: java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at sun.java2d.SunGraphicsEnvironment.getFontManagerForSGE(SunGraphicsEnvironment.java:190)
	at sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(SunGraphicsEnvironment.java:224)
	at sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(SunGraphicsEnvironment.java:252)
	at sun.java2d.HeadlessGraphicsEnvironment.getAvailableFontFamilyNames(HeadlessGraphicsEnvironment.java:94)
	at org.apache.batik.gvt.font.FontFamilyResolver.<clinit>(FontFamilyResolver.java:74)
	... 68 more
```

**Comment by GYiyouth** [comment]
I have to use OpenJDK, and cannot install font family when the task start...

**Comment by nidi3** [comment]
This looks like a bug/missconfiguration in the JDK to me as `GraphicsEnvironment.getAvailableFontFamilyNames()` should not throw a NPE in my opinion.

You can try using the salamander rasterizer: `         g1.rasterize(SALAMANDER).toOutputStream(pngStream);`

Or maybe it's an issue with the default locale, so you can try setting it before: `       Locale.setDefault(Locale.ENGLISH);`

**Comment by nidi3** [comment]
I'm closing this. If you have more informations, feel free to reopen.
