### ISSUE TITLE
StackOverflowError when calling toFile

### ISSUE THREAD

**Issue by wy672515431** [nidi3/graphviz-java#237]
I am using version 0.18.1 and I get a StackOverflowError when trying to output to a file. Here's a minimal example to reproduce the problem:
`MutableGraph graph = mutGraph("example1").setDirected(true).add(
		        mutNode("a").add(Color.RED).addLink(mutNode("b")));
Graphviz.fromGraph(graph).height(100).render(Format.PNG).toFile(file);`

Error message is below.

`at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:112)
	at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:124)
	at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:112)
	at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:124)
	at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:112)
	at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:124)
	at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:112)
	at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:124)
	at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:112)
	at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:124)`

**Comment by wy672515431** [comment]
when I add `Graphviz.useDefaultEngines();` , the error become `guru.nidi.graphviz.engine.GraphvizException: None of the provided engines could be initialized.`
