### ISSUE TITLE
ClassNotFoundException: org.apache.batik.transcoder.TranscoderException

### ISSUE THREAD

**Issue by jeremydouglass** [nidi3/graphviz-java#34]
Based on the examples in README.md, I am trying to parse dot files and render pngs.

However, when calling Graphviz.fromGraph(g) I get the exception:

> ClassNotFoundException: org.apache.batik.transcoder.TranscoderException

I am using the release graphviz-java-0.2.1.jar.

```
import guru.nidi.graphviz.attribute.Records.*;
import guru.nidi.graphviz.model.Compass.*;
import guru.nidi.graphviz.model.Factory.*;
```

```
    for (int i = 0; i <= files.length - 1; i++) {
       try {
         MutableGraph g = Parser.read(files[i]);
         Graphviz.fromGraph(g).width(700).render(Format.PNG).toFile(new File("out.png"));
       } 
       catch(IOException ie) {
         ie.printStackTrace();
       }
     }
```

**Comment by nidi3** [comment]
Hi there
I cannot reproduce this, a few things you could try:
- could you send me a failing dot file?
- is there a complete stacktrace?
- try `.rasterizer(SALAMANDER)`

**Comment by nidi3** [comment]
Is this still an issue?

**Comment by luckyluks** [comment]
I got this exception, when trying the basic example:
1. Creating new Maven-Project in Eclipse
2. Adding dependency to the pom.xml

```
<dependencies>
		<dependency>
			<groupId>guru.nidi</groupId>
			<artifactId>graphviz-java</artifactId>
			<version>0.4.0</version>
		</dependency>
<dependencies>
```
3. Added test class with:
```
import static guru.nidi.graphviz.model.Factory.*;

import java.io.File;
import java.io.IOException;

import guru.nidi.graphviz.engine.Format;
import guru.nidi.graphviz.engine.Graphviz;
import guru.nidi.graphviz.model.Graph;

public class Test {
	public static void main(String[] args) throws IOException {
		Graph g = graph("example1").directed().with(node("a").link(node("b")));
		Graphviz.fromGraph(g).width(200).render(Format.PNG).toFile(new File("example/ex1.png"));
	}
}

```
This is the complete stacktrace:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/batik/transcoder/TranscoderException
	at guru.nidi.graphviz.engine.Rasterizer.<clinit>(Rasterizer.java:23)
	at guru.nidi.graphviz.engine.Graphviz.fromString(Graphviz.java:124)
	at guru.nidi.graphviz.engine.Graphviz.fromGraph(Graphviz.java:138)
	at guru.nidi.graphviz.engine.Graphviz.fromGraph(Graphviz.java:134)
	at testing.Test.main(Test.java:29)
Caused by: java.lang.ClassNotFoundException: org.apache.batik.transcoder.TranscoderException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

**Comment by luckyluks** [comment]
switched back to version 0.2.3 in maven prints following error when trying Maven -> install:

```
Failed to execute goal on project Testing: 
Could not resolve dependencies for project graphicalTesting:graphicalTesting:jar:0.0.1-SNAPSHOT: 
Failed to collect dependencies at guru.nidi:graphviz-java:jar:0.2.3 -> org.apache.xmlgraphics:batik-codec:jar:1.9 -> org.apache.xmlgraphics:batik-awt-util:jar:1.9: 
Failed to read artifact descriptor for org.apache.xmlgraphics:batik-awt-util:jar:1.9: 
Failure to find org.apache.xmlgraphics:batik:pom:1.9 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
```

**Comment by luckyluks** [comment]
switched to version 0.2.4 and added LOGBACK. Now it works for me.
