### ISSUE TITLE
Support Ports in Tables

### ISSUE THREAD

**Issue by schmidt-uni-leipzig** [nidi3/graphviz-java#46]
To draw complex structual objects, one can use in graphviz the HTML TABLE syntax. The following example comes from http://renenyffenegger.ch/notes/tools/Graphviz/examples/index.

```
digraph H {

  parent [
   shape=plaintext
   label=<
     <table border='1' cellborder='1'>
       <tr><td colspan="3">The foo, the bar and the baz</td></tr>
       <tr><td port='port_one'>First port</td><td port='port_two'>Second port</td><td port='port_three'>Third port</td></tr>
     </table>
  >];

  child_one [
   shape=plaintext
   label=<
     <table border='1' cellborder='0'>
       <tr><td>1</td></tr>
     </table>
  >];

  child_two [
   shape=plaintext
   label=<
     <table border='1' cellborder='0'>
       <tr><td>2</td></tr>
     </table>
  >];

  child_three [
   shape=plaintext
   label=<
     <table border='1' cellborder='0'>
       <tr><td>3</td></tr>
     </table>
  >];

  parent:port_one   -> child_one;
  parent:port_two   -> child_two;
  parent:port_three -> child_three;

} 
```

Today, it is not passible to parse nor write such code, because it is not possible to link to ports. There is the Compass Enumeration, but the values defined are fixed. 

When I try to parse such code, I get to following exception

```
java.lang.RuntimeException: <string>:19:26 Invalid compass value 'port_one'
	at guru.nidi.graphviz.model.CreationContext.use(CreationContext.java:40)
	at guru.nidi.graphviz.parse.Parser.parse(Parser.java:56)
	at guru.nidi.graphviz.parse.Parser.read(Parser.java:47)
	at guru.nidi.graphviz.parse.Parser.read(Parser.java:43)
	...
Caused by: <string>:19:26 Invalid compass value 'port_one'
	at guru.nidi.graphviz.parse.Parser.lambda$compass$12(Parser.java:173)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at guru.nidi.graphviz.parse.Parser.compass(Parser.java:172)
	at guru.nidi.graphviz.parse.Parser.nodeId(Parser.java:193)
	at guru.nidi.graphviz.parse.Parser.statement(Parser.java:101)
	at guru.nidi.graphviz.parse.Parser.statementList(Parser.java:84)
	at guru.nidi.graphviz.parse.Parser.lambda$parse$10(Parser.java:72)
	at guru.nidi.graphviz.model.CreationContext.use(CreationContext.java:38)
	... 28 more
```

I recommend to intoduce a new class "Port" implementing LinkSource and LinkTarget . A child class might use the Compass Enumeration. Otherwise, one can define a custom port name. Furthermore, the Serializer class shall support this LinkSource / LinkTarget.

**Comment by nidi3** [comment]
Wow, I did not know this. Going to implement it this week.

**Comment by schmidt-uni-leipzig** [comment]
@nidi3 Thank you very much. It would be nice to have such a feature in your API.

**Comment by nidi3** [comment]
In fact, everything was already there, just some bugs in the Serializer and the Parser.
Just use the record part of a port instead of the compass:
`node("parent").link(between(port("port_one"),node("child_one")))`
Will be possible in the next version.
