### ISSUE TITLE
InvalidPathExpression on Windows

### ISSUE THREAD

**Issue by joerg-rade** [nidi3/graphviz-java#65]
Originating in CommandRunner.which
var1 = "C:\data\apps\apache-maven-3.3.9"\bin

16:20:13,076  [AbstractGraphvizEngine qtp900593187-17 INFO ]  Could not initialize guru.nidi.graphviz.engine.GraphvizCmdLineEngine
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\data\apps\apache-maven-3.3.9"\bin
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at guru.nidi.graphviz.service.CommandRunner.lambda$which$18(CommandRunner.java:78)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at guru.nidi.graphviz.service.CommandRunner.isExecutableFound(CommandRunner.java:110)
	at guru.nidi.graphviz.engine.GraphvizCmdLineEngine.getEngineExecutable(GraphvizCmdLineEngine.java:93)
	at guru.nidi.graphviz.engine.GraphvizCmdLineEngine.doInit(GraphvizCmdLineEngine.java:58)
	at guru.nidi.graphviz.engine.AbstractGraphvizEngine.initTask(AbstractGraphvizEngine.java:42)
	at guru.nidi.graphviz.engine.AbstractGraphvizEngine.init(AbstractGraphvizEngine.java:34)
	at guru.nidi.graphviz.engine.Graphviz.doUseEngine(Graphviz.java:82)
	at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:74)
	at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:55)
	at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:47)
	at guru.nidi.graphviz.engine.Graphviz.getEngine(Graphviz.java:88)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:170)
	at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:68)
	at ife.util.GraphToImage.dotToFile(GraphToImage.java:58)

**Comment by nidi3** [comment]
So `"C:\data\apps\apache-maven-3.3.9"\bin` is a valid windows path, right?
So deleting all `"` in window paths should be ok?
