### ISSUE TITLE
MutableGraph render results with error, which I cannot recreate in Immutable version

### ISSUE THREAD

**Issue by ljader** [nidi3/graphviz-java#78]
Hello.
My MutableGraph is simple 2-node directed graph:
1. node "A" with own random color
2. node "B" with own random color
3. I want the link from A -> B to be the same color as node "B"

This is the generated command:
```
render('digraph { "A" ["color"="#c323a9"] "B" ["color"="#ad7bee"] "A" ["color"="#c323a9"] -> "B" ["color"="#ad7bee"] ["color"="#ad7bee"] }',{format:'svg',engine:'dot'});
```

The mutable version ends with exception:
```
Exception in thread "main" guru.nidi.graphviz.engine.GraphvizException: Error: syntax error in line 1 near '->'
	at guru.nidi.graphviz.engine.ResultHandler.waitFor(ResultHandler.java:42)
	at guru.nidi.graphviz.engine.GraphvizV8Engine$Env.execute(GraphvizV8Engine.java:89)
	at guru.nidi.graphviz.engine.GraphvizV8Engine.jsExecute(GraphvizV8Engine.java:66)
	at guru.nidi.graphviz.engine.AbstractJsGraphvizEngine.execute(AbstractJsGraphvizEngine.java:28)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:177)
	at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:74)
	at guru.nidi.graphviz.engine.Renderer.toFile(Renderer.java:51)
	at pl.ljader.graphviz.error.ErrorMutableGraph.main(ErrorMutableGraph.java:34)
```

My mutable graph code:
```
public class ErrorMutableGraph {
	public static void main(String[] args) throws IOException {
		Color colorA = Color.rgb(RandomStringUtils.random(6, "0123456789abcdef"));
		Color colorB = Color.rgb(RandomStringUtils.random(6, "0123456789abcdef"));

		MutableNode nodeA = mutNode("A").add(colorA);
		MutableNode nodeB = mutNode("B").add(colorB);

		Link link = Link.between(nodeA, nodeB).attrs().add(colorB);
		nodeA.links().add(link);

		MutableGraph graph = mutGraph().setDirected(true);
		graph.add(nodeA, nodeB);

		File file = File.createTempFile("graph_" + System.currentTimeMillis() + "_", ".png");
		Graphviz.fromGraph(graph).width(800).render(Format.PNG).toFile(file);

		System.out.println(file.getAbsolutePath());
	}
}
```

Could you help me to create this graph?

**Comment by nidi3** [comment]
Now, `MutableNode.link().add()` works as expected. So the above code is correct now.
