### ISSUE TITLE
How to add line break in Label.html

### ISSUE THREAD

**Issue by luxmar** [nidi3/graphviz-java#89]
Is there a way to add a line break at the HTML text inside a Label.html element?

```
<br>
</br>
```
are not working

It ends up in an exception, like
`SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "main" guru.nidi.graphviz.engine.GraphvizException: Error: in label of node e

	at guru.nidi.graphviz.engine.ResultHandler.waitFor(ResultHandler.java:42)
	at guru.nidi.graphviz.engine.GraphvizJdkEngine.jsExecute(GraphvizJdkEngine.java:45)
	at guru.nidi.graphviz.engine.AbstractJsGraphvizEngine.execute(AbstractJsGraphvizEngine.java:28)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:186)
	at guru.nidi.graphviz.engine.Renderer.toString(Renderer.java:46)
	at guru.nidi.graphviz.engine.Renderer.toFile(Renderer.java:58)
	at Mining.main(AppHeuristicMining.java:353)`

**Comment by nidi3** [comment]
`<br/>` works, or `\n` in a non-html label

**Comment by nidi3** [comment]
Added an example for this to readme
