### ISSUE TITLE
NPE in GraphvizV8Engine during initialization fail

### ISSUE THREAD

**Issue by joaoe** [nidi3/graphviz-java#91]
Hi.

While I was setting up my project, I started getting this NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at guru.nidi.graphviz.engine.GraphvizV8Engine.release(GraphvizV8Engine.java:38)
	at guru.nidi.graphviz.engine.AbstractGraphvizEngine.initTask(AbstractGraphvizEngine.java:46)
	at guru.nidi.graphviz.engine.AbstractGraphvizEngine.init(AbstractGraphvizEngine.java:34)
	at guru.nidi.graphviz.engine.Graphviz.doUseEngine(Graphviz.java:82)
	at guru.nidi.graphviz.engine.Graphviz.lambda$doUseEngine$15(Graphviz.java:82)
	at guru.nidi.graphviz.engine.AbstractGraphvizEngine.initTask(AbstractGraphvizEngine.java:47)
	at guru.nidi.graphviz.engine.AbstractGraphvizEngine.init(AbstractGraphvizEngine.java:34)
	at guru.nidi.graphviz.engine.Graphviz.doUseEngine(Graphviz.java:82)
	at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:74)
	at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:55)
	at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:47)
	at guru.nidi.graphviz.engine.Graphviz.getEngine(Graphviz.java:88)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:170)
	at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:68)
	at guru.nidi.graphviz.engine.Renderer.toFile(Renderer.java:46)
```

The issue: `GraphvizV8Engine.message` is `null`

`messages` is not set because `GraphvizV8Engine.doInit` is crashing with `java.lang.UnsatisfiedLinkError: Could not load J2V8 library`.  While the latter exception tells me something is wrong with my setup, the former felt like a bug which forced me to debug into the library.

A `null` check ought to be enough for everyone. Thank you.

**Comment by nidi3** [comment]
I suspect you're using an old version, I could not reproduce the issue. Can you try with 0.8.0?

**Comment by joaoe** [comment]
Doh, you are correct. Don't know why, someone decided to use version 0.2 :p
